### ISSUE TITLE
BACKEND: Database Integration

### ISSUE THREAD

**Issue by Clxiu** [tonypioneer/Trust-Indicator#39]
## Description
Design data models for core entities that will map to the database tables; design repositories for the EF data models;

## Why
Required for backend development

## Closing Criteria
- [x] Implement database migrations and set up a database connection string.
- [x] Define Entity Framework Data Models.
- [x] Implement Repositories for Data models. 
- [x] Setup data validation.

**Comment by Clxiu** [comment]
Finished setting up the database, defined data models and created repository classes. 
Data validation is only available for username, password and email.

**Comment by Clxiu** [comment]
Basically finished Repo and Dtos. 
Might need to add more functions in Repo in future development.

**Comment by tonypioneer** [comment]
Close as completed.
